apiVersion: v1
kind : Secret 
metadata:
  name: api-secret
type: Opaque
data: 
  OPENSENSE_BOX_IDS: NWU4ZTA2YzkzZWIyMjYwMDFiZWNkMmY2LDVlZDkyN2VmZDA1NDViMDAxY2Y2MGY2Ziw1ZjljN2FlYjQ2NTkyYjAwMWJhM2Y2Y2Y=